# Copy the custom apps folder to a separate repo

name: Custom apps manifest copy

on:
  push:
    branches: [ "main" ]
    paths: [ "custom-apps/**" ]
  workflow_dispatch:

jobs:
  copy:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create deploy folder
      run: mkdir ./custom-apps/deploy
    - name: Copy manifest
      run: cp ./custom-apps/manifest.json ./custom-apps/deploy/manifest.json
    - name: Copy Readme
      run: cp ./custom-apps/README.md ./custom-apps/deploy/README.md
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:Pithaya/spicetify-apps-dist.git
        BRANCH: main
        FOLDER: ./custom-apps/deploy
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      
