# Copy the custom apps folder to a separate repo

name: Custom apps manifest copy

on:
  push:
    branches: [ "main" ]
    paths: [ "custom-apps/**" ]
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create deploy folder
      run: mkdir deploy
    - name: Copy manifest
      run: cp manifest.json ./deploy/manifest.json
    - name: Copy Readme
      run: cp README.md ./deploy/README.md
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:Pithaya/spicetify-apps-dist.git
        BRANCH: main
        FOLDER: ./deploy
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      
