# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Eternal Jukebox Publish

on:
    push:
        branches: ['main']
        paths: ['custom-apps/eternal-jukebox/**']
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./custom-apps/eternal-jukebox

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
                  cache-dependency-path: ./package-lock.json
            - name: Install dependencies
              working-directory: ./
              run: npm ci
            - name: Build
              run: npm run build-local
            - name: Copy Readme
              run: cp README.md ./dist/README.md
            - name: Copy preview
              run: cp preview.png ./dist/preview.png
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: git@github.com:Pithaya/spicetify-apps-dist.git
                  BRANCH: dist/eternal-jukebox
                  FOLDER: ./custom-apps/eternal-jukebox/dist
                  SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
